[[redirects]]
from = "/contrast/"
to = "/.netlify/functions/onrequest"
status = 200
force = true
_generated_by_eleventy_serverless = "onrequest"

[[redirects]]
from = "/screenshot/*"
to = "/.netlify/builders/screenshot"
status = 200
force = true
